### ISSUE TITLE
HIP build with >=rocm-6.3.0 fails (composable-kernel update request)

### ISSUE THREAD

**Issue by AngryLoki** [RenderKit/oidn#250]
Hi, as new version of rocm components now uses newer Clang (approximately 19.1.0), oidn can not be compiled as clang-19 complains for few errors:

1) this error was fixed in https://github.com/ROCm/composable_kernel/commit/c44137838e2cb30bbe5a3b9903c357b476a34d52
```
/src/oidn/devices/hip/../../external/composable_kernel/include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp:785:32: error: no member named 'a_origin' in 'BlockwiseGemmXdlops_v2<BlockSize, FloatAB, FloatAcc, ATileDesc, BTileDesc, AMmaTileDesc, BMmaTileDesc, MPerBlock, NPerBlock, KPerBlock, MPerXDL, NPerXDL, MRepeat, NRepeat, KPack, TransposeC, AMmaKStride, BMmaKStride>'
  785 |         : a_thread_copy_(other.a_origin), b_thread_copy_(other.b_origin)
      |                          ~~~~~ ^
```

2) these group of errors was fixed in https://github.com/ROCm/composable_kernel/commit/922e42a039a42770446c42fabc62fe1e7b050625 and other commits (i. e. for `blockwise_gemm_xdlops.hpp` code was refactored)
```
/src/oidn/devices/hip/../../external/composable_kernel/include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp:957:42: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
  957 |                     xdlops_gemm.template Run(
      |                                          ^
19 warnings and 5 errors generated when compiling for gfx1030
```

Both of these issues were fixed in recent releases (e. g. 6.3.0). 

As API for `DeviceGroupedConvFwdMultipleD_Wmma_CShuffle` in rocm-6.3.x I also noticed that changing configuration to another one improves performance of oidnBenchmark by 15% (while running on 7900XTX, gfx1100). I'll provide a pull-request with my results, thanks!

**Comment by atafra** [comment]
Thanks a lot, I'll take a look!

**Comment by mattmcadoo** [comment]
Any update on this?

**Comment by atafra** [comment]
I'm currently looking into this. There are some issues with compilation on Windows. It seems `composable_kernel` requires a patch. @AngryLoki have you tried to build this on Windows?

**Comment by Nielsbishere** [comment]
@atafra I'm not sure if it's a different issue, but on devel I do have trouble building the HIP kernel too when I followed the dependency guide on the readme. SYCL, CPU and CUDA all build fine though.
```
FAILED: CMakeFiles/OpenImageDenoise_device_hip.dir/ck_conv_wmma.cpp.obj
C:\PROGRA~1\AMD\ROCm\6.2\bin\CLANG_~1.EXE -DNOMINMAX -DOpenImageDenoise_device_hip_EXPORTS -DUSE_PROF_API=1 -D_CRT_SECURE_NO_WARNINGS -D_WIN -D__HIP_PLATFORM_AMD__=1 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -IE:/oidn/devices/hip/../../external/composable_kernel/include -IE:/oidn/devices/hip/../../external/composable_kernel/library/include -isystem E:/oidn -isystem E:/oidn/external -isystem E:/oidn/build -isystem "C:/Program Files/AMD/ROCm/6.2/include" -Wno-pass-failed -Wno-unneeded-internal-declaration  -O0 -g -Xclang -gcodeview  -std=c++17 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -Wno-unused-result -Wno-ignored-attributes -x hip --offload-arch=gfx902,gfx909,gfx90c,gfx1030,gfx1031,gfx1032,gfx1033,gfx1034,gfx1035,gfx1036,gfx1100,gfx1101,gfx1102,gfx1103 -mcumode -mno-wavefrontsize64 -MD -MT CMakeFiles/OpenImageDenoise_device_hip.dir/ck_conv_wmma.cpp.obj -MF CMakeFiles\OpenImageDenoise_device_hip.dir\ck_conv_wmma.cpp.obj.d -o CMakeFiles/OpenImageDenoise_device_hip.dir/ck_conv_wmma.cpp.obj -c E:/oidn/devices/hip/ck_conv_wmma.cpp
In file included from E:/oidn/devices/hip/ck_conv_wmma.cpp:6:
In file included from E:/oidn/devices/hip/../../external/composable_kernel/include\ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_d_wmma_cshuffle.hpp:12:
In file included from E:/oidn/devices/hip/../../external/composable_kernel/include\ck/utility/common_header.hpp:46:
E:/oidn/devices/hip/../../external/composable_kernel/include\ck/utility/amd_inline_asm.hpp:212:21: error: instruction not supported on this GPU
  212 |     asm volatile("\n \
      |                     ^
<inline asm>:2:14: note: instantiated into assembly here
    2 |              v_dot4_i32_i8 v6, v7, v8, v6
      |              ^
```

**Comment by atafra** [comment]
@Nielsbishere Are you trying to build in Debug mode? This seems to be either a compiler or AMD Composable Kernel issue. It's not possible to build the AMD Composable Kernel library which OIDN uses in Debug mode.

Apart from this, ROCm 6.3.0+ is now supported in the `devel` branch.
